name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    # Krok 1: Pobierz kod repozytorium
    - name: Checkout code
      uses: actions/checkout@v4

    # Krok 2: Ustaw Python 3.8
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Krok 3: Zainstaluj zależności systemowe
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libffi-dev \
          libssl-dev \
          autoconf \
          autotools-dev \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libltdl-dev \
          libsqlite3-dev \
          git \
          zip \
          unzip \
          openjdk-8-jdk \
          python3-pip

    # Krok 4: Zainstaluj zależności Python
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.36
        pip install buildozer==1.5.0

    # Krok 5: Zainstaluj Android SDK i NDK
    - name: Install Android SDK
      uses: android-actions/setup-android@v2

    - name: Install Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r23b
        add-to-path: true

    # Krok 6: Akceptuj licencje Android SDK
    - name: Accept Android SDK licenses
      run: |
        yes | sdkmanager --licenses || true

    # Krok 7: Konfiguruj środowisko Buildozer
    - name: Configure Buildozer
      run: |
        mkdir -p ~/.buildozer
        echo "[buildozer]" > ~/.buildozer/buildozer.spec
        echo "log_level = 2" >> ~/.buildozer/buildozer.spec

    # Krok 8: Kompiluj APK
    - name: Build APK
      run: |
        buildozer android debug
      env:
        ANDROID_NDK_HOME: ${{ env.ANDROID_NDK_ROOT }}
        ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}
        BUILDOZER_WARN_ON_ROOT: 1

    # Krok 9: Zapisz artefakty
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: bin/*.apk

    # Krok 10: Zapisz logi Buildozer (do debugowania)
    - name: Upload Buildozer logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: buildozer-logs
        path: .buildozer/logs/
