name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    container:
      image: kivy/buildozer:latest

    steps:
    # Krok 1: Pobierz kod repozytorium
    - name: Checkout code
      uses: actions/checkout@v4

    # Krok 2: Wyświetl informacje o środowisku
    - name: Display environment info
      run: |
        echo "Python version: $(python --version)"
        echo "Pip version: $(pip --version)"
        echo "Buildozer version: $(buildozer --version)"
        echo "NDK path: $ANDROID_NDK_HOME"
        echo "SDK path: $ANDROID_SDK_ROOT"

    # Krok 3: Zainstaluj dodatkowe zależności
    - name: Install additional dependencies
      run: |
        pip install cython==3.0.2

    # Krok 4: Kompiluj APK z pełnym logowaniem
    - name: Build APK
      run: |
        buildozer android debug 2>&1 | tee buildozer.log
      env:
        ANDROID_NDK_HOME: $ANDROID_NDK_HOME
        ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT

    # Krok 5: Sprawdź zawartość katalogów
    - name: Check directories
      if: always()
      run: |
        echo "=== Listing .buildozer directory ==="
        find .buildozer -type f | head -20
        echo "=== Listing bin directory ==="
        find bin -type f 2>/dev/null || echo "bin directory does not exist"
        echo "=== Looking for APK files ==="
        find . -name "*.apk" 2>/dev/null || echo "No APK files found"

    # Krok 6: Zapisz artefakty
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with:
        name: app-debug
        path: |
          bin/*.apk
          ./*.apk

    # Krok 7: Zapisz logi Buildozer
    - name: Upload Buildozer logs
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with:
        name: buildozer-logs
        path: |
          .buildozer/logs/
          buildozer.log
          .buildozer/buildozer.log

    # Krok 8: Zapisz pełny log kompilacji
    - name: Upload build log
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with:
        name: build-log
        path: buildozer.log
